### ISSUE TITLE
添加记住用户设置的功能

### ISSUE THREAD

**Issue by zzhzero** [GlossMod/RDR2NativeTrainer#1]

**Comment by 3DMXM** [comment]
你想实现的话，可以自己实现，

如果我没记错的话，在每项功能的 class 里面调用 SetState(value) 就可以设置对应的值, 

只要在每次修改的时候记录到一个本地文件，比如说 save.json ， 然后在每次启动的时候读取 save.json 中的内容对所有选项进行设置

就能实现记住的功能。
